application:
  hooks:
    post-app-build: mkdir -p dist/application/actions
  runtimeManifest:
    database:
      auto-provision: true
      region: amer
    packages: {}
extensions:
  commerce/backend-ui/1:
    $include: src/commerce-backend-ui-1/ext.config.yaml
  commerce/configuration/1:
    $include: src/commerce-configuration-1/ext.config.yaml
  commerce/extensibility/1:
    $include: src/commerce-extensibility-1/ext.config.yaml
