webhook:
  function: ../../../../build/actions/renewal-notification/webhook/index.js
  web: 'yes'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
    IMS_OAUTH_S2S_CLIENT_ID: $IMS_OAUTH_S2S_CLIENT_ID
    IMS_OAUTH_S2S_CLIENT_SECRET: $IMS_OAUTH_S2S_CLIENT_SECRET
    IMS_OAUTH_S2S_ORG_ID: $IMS_OAUTH_S2S_ORG_ID
    IMS_OAUTH_S2S_SCOPES: $IMS_OAUTH_S2S_SCOPES
    COMMERCE_BASE_URL: $COMMERCE_BASE_URL
    COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
    COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
    COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
    COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
    PRICE_CHANGE_INTERNAL_EVENTS_PROVIDER_ID: $PRICE_CHANGE_INTERNAL_EVENTS_PROVIDER_ID
  annotations:
    require-adobe-auth: true
    final: true
  limits:
    timeout: 55000
    memory: 512
upload:
  function: ../../../../build/actions/renewal-notification/upload/index.js
  web: 'yes'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
    IMS_OAUTH_S2S_CLIENT_ID: $IMS_OAUTH_S2S_CLIENT_ID
    IMS_OAUTH_S2S_CLIENT_SECRET: $IMS_OAUTH_S2S_CLIENT_SECRET
    IMS_OAUTH_S2S_ORG_ID: $IMS_OAUTH_S2S_ORG_ID
    IMS_OAUTH_S2S_SCOPES: $IMS_OAUTH_S2S_SCOPES
  annotations:
    require-adobe-auth: true
    final: true
  limits:
    timeout: 300000
    memory: 1024
list:
  function: ../../../../build/actions/renewal-notification/list/index.js
  web: 'yes'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
    IMS_OAUTH_S2S_CLIENT_ID: $IMS_OAUTH_S2S_CLIENT_ID
    IMS_OAUTH_S2S_CLIENT_SECRET: $IMS_OAUTH_S2S_CLIENT_SECRET
    IMS_OAUTH_S2S_ORG_ID: $IMS_OAUTH_S2S_ORG_ID
    IMS_OAUTH_S2S_SCOPES: $IMS_OAUTH_S2S_SCOPES
  annotations:
    require-adobe-auth: true
    final: true
  limits:
    timeout: 55000
    memory: 512
