pre-renewal-persist-consumer:
  function: ../../../../build/actions/external-events/pre-renewal-persist-consumer/index.js
  web: 'no'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
    IMS_OAUTH_S2S_CLIENT_ID: $IMS_OAUTH_S2S_CLIENT_ID
    IMS_OAUTH_S2S_CLIENT_SECRET: $IMS_OAUTH_S2S_CLIENT_SECRET
    IMS_OAUTH_S2S_ORG_ID: $IMS_OAUTH_S2S_ORG_ID
    IMS_OAUTH_S2S_SCOPES: $IMS_OAUTH_S2S_SCOPES
    PRICE_CHANGE_INTERNAL_EVENTS_PROVIDER_ID: $PRICE_CHANGE_INTERNAL_EVENTS_PROVIDER_ID
  annotations:
    final: true
  limits:
    timeout: 300000
    memory: 512
reporting-delivery-consumer:
  function: ../../../../build/actions/external-events/reporting-delivery-consumer/index.js
  web: 'no'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
  annotations:
    final: true
  limits:
    timeout: 300000
    memory: 512
