operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
hooks:
  pre-app-build: hooks/pre-app-build.js
  pre-app-deploy: hooks/pre-app-deploy.js
runtimeManifest:
  packages:
    admin-ui-sdk:
      license: Apache-2.0
      actions:
        $include: actions/admin-ui-sdk/actions.config.yaml
    application-crons:
      license: Apache-2.0
      actions:
        $include: actions/application-crons/actions.config.yaml
      triggers:
        $include: actions/application-crons/triggers.config.yaml
      rules:
        $include: actions/application-crons/rules.config.yaml
    external-events:
      license: Apache-2.0
      actions:
        $include: actions/external-events/actions.config.yaml
    price-change:
      license: Apache-2.0
      actions:
        $include: actions/price-change/actions.config.yaml
    renewal:
      license: Apache-2.0
      actions:
        $include: actions/renewal/actions.config.yaml
      apis:
        $include: actions/renewal/apis.config.yaml
